// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuCitUtv1KNdInfrxggmNOcUJpbj6Be-8',
    appId: '1:571868944783:web:82cf53558a88f60b6cd3fa',
    messagingSenderId: '571868944783',
    projectId: 'todo-flutter-db43f',
    authDomain: 'todo-flutter-db43f.firebaseapp.com',
    storageBucket: 'todo-flutter-db43f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgk3cGAC7gQ-azz0klVT_mAahljpV0sdU',
    appId: '1:571868944783:android:33dede35c94f21036cd3fa',
    messagingSenderId: '571868944783',
    projectId: 'todo-flutter-db43f',
    storageBucket: 'todo-flutter-db43f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2qxkuBRiOetUkMoenT1SofF63XRLBNrQ',
    appId: '1:571868944783:ios:93cf952b10c447266cd3fa',
    messagingSenderId: '571868944783',
    projectId: 'todo-flutter-db43f',
    storageBucket: 'todo-flutter-db43f.appspot.com',
    iosClientId: '571868944783-4eiuce9rnuujp3pm80jo3v335teeprek.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2qxkuBRiOetUkMoenT1SofF63XRLBNrQ',
    appId: '1:571868944783:ios:93cf952b10c447266cd3fa',
    messagingSenderId: '571868944783',
    projectId: 'todo-flutter-db43f',
    storageBucket: 'todo-flutter-db43f.appspot.com',
    iosClientId: '571868944783-4eiuce9rnuujp3pm80jo3v335teeprek.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuCitUtv1KNdInfrxggmNOcUJpbj6Be-8',
    appId: '1:571868944783:web:05bb0fec3f79cdb46cd3fa',
    messagingSenderId: '571868944783',
    projectId: 'todo-flutter-db43f',
    authDomain: 'todo-flutter-db43f.firebaseapp.com',
    storageBucket: 'todo-flutter-db43f.appspot.com',
  );

}